version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /pullventure_server/
    destination: /home/ec2-user/serverpod/upload/pullventure_server/
hooks:
  BeforeInstall:
    - location: pullventure_server/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: pullventure_server/aws/scripts/start_server
      timeout: 300
      runas: root
