version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pullventure
      POSTGRES_PASSWORD: "zYMtJ824G3Zew55hWhb1_40M5_kU-4Jy"
    volumes:
      - pullventure_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "I1QQacc1OMvmSyiBj6M_NZmcYR2Fg2dW"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  pullventure_data:
